import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: ["/favicon.ico"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"winduu"}>
        <div className="winduu_front min-h-screen flex flex-col">
          <Header />
          <div className="wrapper flex-1 mt-16">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
